export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://vpnkollen.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/streaming","priority":"0.8","changefreq":"weekly"},{"path":"/torrenting","priority":"0.8","changefreq":"weekly"},{"path":"/mobil","priority":"0.8","changefreq":"weekly"},{"path":"/gratis","priority":"0.8","changefreq":"weekly"},{"path":"/billigast","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-mullvad","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-expressvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-surfshark","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-cyberghost","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-proton-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-pia-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordvpn-vs-hide-me","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mullvad-vs-expressvpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mullvad-vs-surfshark","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mullvad-vs-cyberghost","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mullvad-vs-proton-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mullvad-vs-pia-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/mullvad-vs-hide-me","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-surfshark","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-cyberghost","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-proton-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-pia-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/expressvpn-vs-hide-me","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-cyberghost","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-proton-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-pia-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/surfshark-vs-hide-me","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-proton-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-pia-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cyberghost-vs-hide-me","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proton-vpn-vs-pia-vpn","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proton-vpn-vs-hide-me","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/pia-vpn-vs-hide-me","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-23</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }